### ISSUE TITLE
Release/tag

### ISSUE THREAD

**Issue by slavkoja** [bmrzycki/stunip#1]
Please, add release/tag, to simplify packaging/update tracking.

I tried it and it works as described, thus i intent to package it for debian (public personal repo) to i can easy install it on all my machines (where needed), tagging will simplify things, as tracking git changes is not as easy.

regards

**Comment by bmrzycki** [comment]
Hello @slavkoja , I've added tags to denote where I consider the code released. The latest is 1.2.0.

Thanks for using/packaging the tool!

**Comment by slavkoja** [comment]
thanks ;-)
